
service: docs
runtime: python27
api_version: 1
threadsafe: true
manual_scaling:
  instances: 1

handlers:
# Handle the main page by serving the index page.
# Note the $ to specify the end of the path, since app.yaml does prefix matching.
- url: /$
  static_files: site/index.html
  upload: site/index.html

# Handle folder urls by serving the index.html page inside.
- url: /(.*)/$
  static_files: site/\1/index.html
  upload: site/.*/index.html

# Handle nearly every other file by just serving it.
- url: /(.+)
  static_files: site/\1
  upload: site/(.*)