site_name: OneAtlas Playground Documentation
site_url: http://playground-docs.readthedocs.io/
site_author: OneAtlas Playground
repo_url: http://github.com/airbusgeo/playground-docs/

theme: readthedocs

extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  logo: 'images/logo_airbus_A.png'

extra_css:
  - stylesheets/swagger-ui.css

extra_javascript:
  - scripts/swagger-ui-bundle.js
  - scripts/swagger-ui-standalone-preset.js

markdown_extensions:
  - admonition

copyright: 'Copyright &copy; 2018 - Airbus Defence and Space - Intelligence'

pages:
  - OneAtlas Playground: index.md
  - Create a custom process:
    - Create a custom process: processing/process.md
    - Build a container image: processing/docker.md
    - Use from in OneAtlas Playground: processing/use.md
    - (optional) Deploy on GCE: processing/deploy_gce.md
    - (optional) Deploy on GKE: processing/deploy_gke.md
    - Sample application: processing/sample.md
  - Airbus DS Geo APIs:
    - Geo Process API: processing/geo_process_api.md
    - Geo Processes Manager API: process_manager/geo_processes_manager_api.md
    - Airbus DS JSON Schema metadata extensions: processing/ads_json_extensions.md
  - Playground Process APIs:
    - Object Detection template: processing/object_detection.md
    - Change Detection template: processing/change_detection.md
  - Playground APIs:
    - Geo Processes Manager API: process_manager/geo_processes_manager_playground.md
    - Object Detection template: process_manager/object_detection.md
    - Change Detection template: process_manager/change_detection.md
    - Geo Data Manager API: data_manager/geo_data_manager_playground.md
  - Exported Data:
    - One Atlas: parsing/one-atlas-data.md
    - Export Data Format: parsing/parsing.md
  - Playground usage:
    - Web interface: web/interface.md
    - Datasets: web/dataset.md
    - Validation: web/validation.md
    - Processing: web/processing.md
    - Jobs: web/job.md
