site_name: OneAtlas Playground Documentation
site_url: # TO FILL
site_author: OneAtlas Playground
repo_url: # TO FILL

theme: readthedocs

# Copyright
copyright: 'Copyright &copy; 2017 - Airbus Defence and Space - Intelligence'

pages:
  - OneAtlas Playground: index.md
  - Service Deployment:
    - Packaging your Predictor: service/packaging.md
    - Builiding your Docker: service/docker.md
    - Deployment Process on Playground: service/deploy.md
  - Using OneAtlas Web Interface:
    - Using OneAtlas Playground Web Interface: web/interface.md
    - Tagging Datasets on OneAtlas: web/tag.md
  - Ship Detection:
    - Ship Recognition Database: ship/ship.md