site_name: OneAtlas Playground Documentation
site_url: http://playground-docs.readthedocs.io/
site_author: OneAtlas Playground
repo_url: http://github.com/airbusgeo/playground-docs/

theme: readthedocs

extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  logo: 'images/logo_airbus_A.png'

extra_css:
  - stylesheets/swagger-ui.css

extra_javascript:
  - scripts/swagger-ui-bundle.js
  - scripts/swagger-ui-standalone-preset.js

markdown_extensions:
  - admonition

copyright: 'Copyright &copy; 2018 - Airbus Defence and Space - Intelligence'

pages:
  - OneAtlas Playground: index.md
  - Using OneAtlas Playground:
    - Web interface: web/interface.md
    - Datasets: web/dataset.md
    - Validation: web/validation.md
    - Processing: web/processing.md
    - Jobs: web/job.md
  - Using OneAtlas Playground Data:
    - One Atlas: parsing/one-atlas-data.md
    - Export Data Format: parsing/parsing.md
  - Creating a Custom Process:
    - Create a custom process: processing/process.md
    - Build a container image: processing/docker.md
    - Deploy on GCE: processing/deploy_gce.md
    - Deploy on GKE: processing/deploy_gke.md
    - Use from Playground: processing/use.md
    - Sample application: processing/sample.md
  - Geo Process API: processing/geo_process_api.md
  - Process Templates for OneAtlas Playground:
      - Object detection: processing/object_detection.md
      - Change detection: processing/change_detection.md
